# Currently unused
PIDs = \
{
    'PIDs Supported [1-20]': '00',
    'Monitor Status': '01',
    'Freeze DTC': '02',
    'Fuel System Status': '03',
    'Engine Load': '04',
    'Coolant Temp': '05',
    'ST Fuel Trim B1': '06',
    'LT Fuel Trim B1': '07',
    'ST Fuel Trim B2': '08',
    'LT Fuel Trim B2': '09',
    'Fuel Pressure': '0A',
    'Intake Manifold Pressure': '0B',
    'Engine RPM': '0C',
    'Vehicle Speed': '0D',
    'Timing Advance': '0E',
    'Intake Air Temp': '0F',
    'MAF Flow Rate': '10',
    'Throttle Position': '11',
    'Secondary Air Status': '12',
    'Oxygen Sensors Present': '13',
    'B1S1 Voltage / ST Fuel Trim': '14',
    'B1S2 Voltage / ST Fuel Trim': '15',
    'B1S3 Voltage / ST Fuel Trim': '16',
    'B1S4 Voltage / ST Fuel Trim': '17',
    'B2S1 Voltage / ST Fuel Trim': '18',
    'B2S2 Voltage / ST Fuel Trim': '19',
    'B2S3 Voltage / ST Fuel Trim': '1A',
    'B2S4 Voltage / ST Fuel Trim': '1B',
    'OBD Standards': '1C',
    'Oxygen Sensors Present v2': '1D',
    'Aux Input Status': '1E',
    'Time Since Last Start': '1F',
    'PIDs Supported [21-40]': '20',
    'Distance Traveled w/ MIL': '21',
    'Fuel Rail Pressure (manifold)': '22',
    'Fuel Rail Pressure (direct)': '23',
    'O2S1_lambda_voltage': '24',
    'O2S2_lambda_voltage': '25',
    'O2S3_lambda_voltage': '26',
    'O2S4_lambda_voltage': '27',
    'O2S5_lambda_voltage': '28',
    'O2S6_lambda_voltage': '29',
    'O2S7_lambda_voltage': '2A',
    'O2S8_lambda_voltage': '2B',
    'Commanded EGR': '2C',
    'EGR Error': '2D',
    'Evap Purge': '2E',
    'Fuel Level': '2F',
    '# of Warm-ups Since Codes Cleared': '30',
    'Distance Traveled Since Codes Cleared': '31',
    'Evap System Pressure': '32',
    'Barometric Pressure': '33',
    'O2S1_lambda_current': '34',
    'O2S2_lambda_current': '35',
    'O2S3_lambda_current': '36',
    'O2S4_lambda_current': '37',
    'O2S5_lambda_current': '38',
    'O2S6_lambda_current': '39',
    'O2S7_lambda_current': '3A',
    'O2S8_lambda_current': '3B',
    'Catalyst Temp B1S1': '3C',
    'Catalyst Temp B2S1': '3D',
    'Catalyst Temp B1S2': '3E',
    'Catalyst Temp B2S2': '3F',
    'PIDs Supported [41-60]': '40',
    'Monitor Status This Drive Cycle': '41',
    'Control Module Voltage': '42',
    'Absolute Load Voltage': '43',
    'A/F Ratio': '44',
    'Relative Throttle Position': '45',
    'Ambient Air Temp': '46',
    'Absolute Throttle Position B': '47',
    'Absolute Throttle Position C': '48',
    'Accelerator Pedal Position D': '49',
    'Accelerator Pedal Position E': '4A',
    'Accelerator Pedal Position F': '4B',
    'Throttle Actuator': '4C',
    'Run Time w/ MIL On': '4D',
    'Time Since Codes Cleared': '4E',
    'Max Values': '4F',
    'MAF Max Value': '50',
    'Fuel Type': '51',
    'Ethanol Fuel %': '52',
    'Absolute Evap Pressure': '53',
    'Evap Vapor Pressure': '54',
    'ST Trim Secondary O2 B1+B3': '55',
    'LT Trim Secondary O2 B1+B3': '56',
    'ST Trim Secondary O2 B2+B4': '57',
    'LT Trim Secondary O2 B2+B4': '58',
    'Absolute Fuel Rail Pressure': '59',
    'Relative Accel Pedal Position': '5A',
    'Hybrid Battery Life Remaining': '5B',
    'Engine Oil Temp': '5C',
    'Fuel Injection Timing': '5D',
    'Engine Fuel Rate': '5E',
    'Emissions Requirements': '5F',
    'PIDs Supported [61-80]': '60',
    'Drivers Demand Torque %': '61',
    'Actual Engine Torque %': '62',
    'Engine Reference Torque': '63',
    'Engine Torque %': '64',
    'Aux In/Out Supported': '65'
    # More
}

for key, value in PIDs.items():
    PIDs[key] = '01 ' + value
